### PR TITLE
Fixed issue with forward slashes in map names

### PR DESCRIPTION
**Pull request by ghost**
I think

### CODE REVIEW

**Comment by tconn89** [comment]
So you want to prepend the name with a random hex string and replace all forward slashes with colons?

Is the random hex string so we can have multiple maps by the same name?  You haven't proposed how we would fetch and clean the file name on load (removing the random string so the user doesn't see it.)

I think forward slashes should be replaced with an empty string `''`
Why don't we just have the client validate that the name is alpha numeric or whatever.

**Comment by ledlamp** [comment]
> Is the random hex string so we can have multiple maps by the same name? You haven't proposed how we would fetch and clean the file name on load (removing the random string so the user doesn't see it.)

Yes, it's to avoid overwriting files
The map_name is separate from the file path in the database so (AFAIK) it doesn't matter what it's named. When client requests a map by name, server will read the file at whatever path is stored in the database and will serve it. I've already implemented the change and it works fine; maps show with their names as usual, in the client.

>I think forward slashes should be replaced with an empty string `' '`

It doesn't matter, but file names without spaces are easier to work with. Maybe we should replace spaces with underscores...

>Why don't we just have the client validate that the name is alpha numeric or whatever.

Because someone could send their own requests to upload a maliciously named file and mess with the server. It's a security hole of the server.
There's no need to prevent usage of punctuation & other characters if we can just escape them like you're supposed to.

**Comment by tconn89** [comment]
> Because someone could send their own requests to upload a maliciously named file and mess 
> with the server. It's a security hole of the server.
> There's no need to prevent usage of punctuation & other characters if we can just escape them 
> like you're supposed to. 

Ok sounds good, I guess it would be optimal to just do both front end and back end validation on forward slash.

This solution is going to take a lot more memory because every new save will have a unique file saved to the server (sort of like unorganized version control), even if its only one map in the database.

**Comment by ledlamp** [comment]
>This solution is going to take a lot more memory because every new save will have a unique file saved to the server (sort of like unorganized version control), even if its only one map in the database. Its a memory leak because there will end up being many files that no WorldMap db entry points to.

Oh, I see. It's writing the uploaded file first, then calling the function to add or update the metadata in the database.
It should check the database first and overwrite the file at the current path if the map exists.

You know, we could just store the data in the _database_ and things would be simpler...
The maximum size of a MongoDB document is 16mb. Our terraindatas get near that, but with compression (todo) they are around 1mb, so there should be no problem.

**Pull request merged**
